// <auto-generated />
using System;
using DevHobby.CourseFlow.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevHobby.CourseFlow.Persistence.Migrations
{
    [DbContext(typeof(DevHobbyDbContext))]
    [Migration("20250331134604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("DevHobby.CourseFlow.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("f7aac0ff-28f0-4427-be8b-41472b9b55db"),
                            Name = "C#"
                        },
                        new
                        {
                            CategoryId = new Guid("d157b292-cf64-47df-815e-298c34ebc7a3"),
                            Name = "Asp.Net Core"
                        },
                        new
                        {
                            CategoryId = new Guid("29db6e39-1b50-4001-960d-4451bbf2b2ad"),
                            Name = "Software Architecture"
                        },
                        new
                        {
                            CategoryId = new Guid("3141995d-9911-48b0-b651-b5ea6aadfc1d"),
                            Name = "Domain Driven Design"
                        },
                        new
                        {
                            CategoryId = new Guid("95057448-5345-4657-9668-c8942a28db26"),
                            Name = "Microservices"
                        });
                });

            modelBuilder.Entity("DevHobby.CourseFlow.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("63bdb34b-9ebc-4703-8985-c7713cab46f7"),
                            Author = "Mariusz Jurczenko",
                            CategoryId = new Guid("f7aac0ff-28f0-4427-be8b-41472b9b55db"),
                            Description = "Czy marzysz o zostaniu programistą, ale nie wiesz, od czego zacząć? \"C# Podstawy Programowania: Twój Pierwszy Krok w Świat Kodowania\" to kurs stworzony z myślą o Tobie! Ten kurs oferuje przystępne wprowadzenie do świata C# - języka, który łączy prostotę dla początkujących z możliwościami dla zaawansowanych użytkowników.",
                            ImageUrl = "https://perfumereverie.com/wp-content/uploads/obrazki/CsharpPodstawy.webp",
                            Name = "C# Podstawy Programowania: Twój Pierwszy Krok w Świat Kodowania",
                            Price = 300,
                            PublicationDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = new Guid("190c6fd6-4b5c-42a6-bcf6-fecc68d66d54"),
                            Author = "Mariusz Jurczenko",
                            CategoryId = new Guid("f7aac0ff-28f0-4427-be8b-41472b9b55db"),
                            Description = "Tematem tego kursu będzie programowanie w języku C #, a dokładnie wszystko co powinieneś wiedzieć o programowaniu obiektowym. Po podaniu specyfikacji nowej funkcji lub nowej aplikacji zacznij od zidentyfikowania klas z wymagań lub specyfikacji. Programowanie obiektowe reprezentuje encje i koncepcje aplikacji jako zbioru klas.",
                            ImageUrl = "https://perfumereverie.com/wp-content/uploads/obrazki/CsharpObiektowka.webp",
                            Name = "C# Podstawy Programowanie Obiektowego",
                            Price = 300,
                            PublicationDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = new Guid("12ef5a63-7dab-41ff-9b33-68ea7bbf9a68"),
                            Author = "Mariusz Jurczenko",
                            CategoryId = new Guid("f7aac0ff-28f0-4427-be8b-41472b9b55db"),
                            Description = "Kiedy po raz pierwszy zacząłem swoją kariera programistyczna, szybko dowiedziałem się, że jest duża różnica między wiedzą, jak pisać kod a wiedzą jak dobrze napisać kod, i tutaj leży wyzwanie.",
                            ImageUrl = "https://perfumereverie.com/wp-content/uploads/obrazki/CsharpNajlepszePraktyki.webp",
                            Name = "C# Najlepsze Praktyki Podstawy Języka",
                            Price = 300,
                            PublicationDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = new Guid("41651ae9-bae0-4311-9052-87b4e902961d"),
                            Author = "Mariusz Jurczenko",
                            CategoryId = new Guid("f7aac0ff-28f0-4427-be8b-41472b9b55db"),
                            Description = "W tym kursie pokażę Ci, jak kodować za pomocą prawdopodobnie najbardziej przydatnych i najczęściej używanych kolekcji, takich jak: tablica, lista, stos, kolejka i słownik oraz, co ważne, kiedy używać każdej z tych kolekcji.",
                            ImageUrl = "https://perfumereverie.com/wp-content/uploads/obrazki/CsharpKolekcje.webp",
                            Name = "C# Wprowadzenie Do Kolekcji",
                            Price = 300,
                            PublicationDate = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = new Guid("b347d23c-0776-4a59-ad9f-b6cce0f70e8e"),
                            Author = "Mariusz Jurczenko",
                            CategoryId = new Guid("f7aac0ff-28f0-4427-be8b-41472b9b55db"),
                            Description = "Ten kurs poświęcony typom generycznym w C# to solidna dawka wiedzy, która pozwoli Ci tworzyć bardziej elastyczny, efektywny i wielokrotnego użytku kod. Nauczysz się, jak korzystać z generyków na różnych poziomach – od podstawowych po zaawansowane koncepcje, takie jak budowanie kontenera wstrzykiwania zależności (Dependency Injection Container).",
                            ImageUrl = "https://perfumereverie.com/wp-content/uploads/obrazki/CsharpGenerics.webp",
                            Name = "C# Generics",
                            Price = 300,
                            PublicationDate = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = new Guid("fdc2a4bb-d08f-4895-95f4-e3f18119f95b"),
                            Author = "Mariusz Jurczenko",
                            CategoryId = new Guid("f7aac0ff-28f0-4427-be8b-41472b9b55db"),
                            Description = "Chcesz nauczyć się programowania gier w C#? Zbuduj od podstaw kultowego Tetrisa i poznaj kluczowe koncepcje programowania! W tym kursie przeprowadzimy Cię przez cały proces – od minimalnej wersji gry (MVP) po bardziej zaawansowane mechaniki i optymalizację. ",
                            ImageUrl = "https://perfumereverie.com/wp-content/uploads/obrazki/CsharpTetris.webp",
                            Name = "C# – Zbuduj Własnego Tetrisa! Kompletny Przewodnik",
                            Price = 300,
                            PublicationDate = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = new Guid("ac955e68-9ec9-45af-9128-fe5312c123a2"),
                            Author = "Mariusz Jurczenko",
                            CategoryId = new Guid("29db6e39-1b50-4001-960d-4451bbf2b2ad"),
                            Description = "Czy chcesz nauczyć się budować skalowalne, testowalne i łatwe w utrzymaniu aplikacje w C#? Jeśli tak, to ten kurs jest dla Ciebie! Poznasz zasady Clean Architecture i nauczysz się stosować je w praktyce, tworząc dobrze zaprojektowane aplikacje w .NET.",
                            ImageUrl = "https://perfumereverie.com/wp-content/uploads/obrazki/CleanArchitecturePraktyce.webp",
                            Name = "C# Clean Architecture w Praktyce",
                            Price = 300,
                            PublicationDate = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = new Guid("13c1ad99-cfa2-410d-8cdb-c15cd3808871"),
                            Author = "Mariusz Jurczenko",
                            CategoryId = new Guid("d157b292-cf64-47df-815e-298c34ebc7a3"),
                            Description = "Ten kurs nauczy Cię kompleksowego tworzenia aplikacji webowych przy użyciu ASP.NET Core, Entity Framework Core oraz Angular. Obejmuje zarówno backend, jak i frontend, w tym funkcje takie jak uwierzytelnianie, integracja z bazami danych i systemy przesyłania wiadomości. Kurs jest idealny dla początkujących programistów oraz osób pragnących zrealizować swój własny projekt.",
                            ImageUrl = "https://perfumereverie.com/wp-content/uploads/obrazki/PortalRandkowy.webp",
                            Name = "Zbuduj Profesjonalny Portal Randkowy od Podstaw!",
                            Price = 800,
                            PublicationDate = new DateTime(2024, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = new Guid("3c420bf1-0580-4648-8c1e-5ea2bc6d7155"),
                            Author = "Mariusz Jurczenko",
                            CategoryId = new Guid("d157b292-cf64-47df-815e-298c34ebc7a3"),
                            Description = "Ten kurs to kompleksowy przewodnik po budowie aplikacji CMS i sklepu internetowego z wykorzystaniem ASP.NET MVC. Projekt łączy w sobie funkcjonalność systemu zarządzania treścią (CMS) oraz sklepu internetowego, a dodatkowo jest zintegrowany z systemem płatności PayPal. Podczas kursu dowiesz się, jak stworzyć pełnoprawną aplikację webową, opanowując nowoczesne techniki i narzędzia używane w rzeczywistych projektach. ",
                            ImageUrl = "https://perfumereverie.com/wp-content/uploads/obrazki/cmsshop.webp",
                            Name = "CMS Shop Paypal - Praktyczny projekt",
                            Price = 600,
                            PublicationDate = new DateTime(2024, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = new Guid("fcd6c1d3-da1a-4dc2-bd9e-585d983d9920"),
                            Author = "Mariusz Jurczenko",
                            CategoryId = new Guid("d157b292-cf64-47df-815e-298c34ebc7a3"),
                            Description = "W kursie będziemy budować naszą pierwszą aplikację ASP.NET Core 2.1 MVC z Visual Studio 2017. Ten kurs ma na celu dać ci praktyczny sposób, aby dowiedzieć się jak najwięcej o ASP.NET Core 2.1 MVC.",
                            ImageUrl = "https://perfumereverie.com/wp-content/uploads/obrazki/aspnetcore.webp",
                            Name = "ASP.NET Core 2.1 MVC - Pierwsza Aplikacja",
                            Price = 200,
                            PublicationDate = new DateTime(2024, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = new Guid("2d548535-86f8-4b9a-b4ec-1570362dad75"),
                            Author = "Mariusz Jurczenko",
                            CategoryId = new Guid("d157b292-cf64-47df-815e-298c34ebc7a3"),
                            Description = "Kurs ten poprowadzi Cię krok po kroku przez budowę nowoczesnej aplikacji sklepu internetowego z wykorzystaniem ASP.NET MVC i najważniejszych technologii związanych z tworzeniem aplikacji webowych. Nauczysz się, jak tworzyć funkcjonalne aplikacje od podstaw, zarządzać danymi, obsługiwać użytkowników i budować przyjazny interfejs. Wszystko to w oparciu o praktyczne przykłady i z użyciem najlepszych narzędzi dostępnych w ekosystemie ASP.NET.",
                            ImageUrl = "https://perfumereverie.com/wp-content/uploads/obrazki/aspnetmvc.webp",
                            Name = "Asp.Net MVC Praktyczny Kurs",
                            Price = 200,
                            PublicationDate = new DateTime(2024, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = new Guid("f11ba266-1618-49e6-ba9b-5896e668d789"),
                            Author = "Mariusz Jurczenko",
                            CategoryId = new Guid("d157b292-cf64-47df-815e-298c34ebc7a3"),
                            Description = "Przygotuj się na intensywną dawkę wiedzy i praktyki, która pozwoli Ci rozpocząć tworzenie nowoczesnych, responsywnych stron internetowych. Ten kurs jest idealny dla tych, którzy chcą szybko zdobyć umiejętności potrzebne do pracy z technologiami webowymi po stronie klienta. ",
                            ImageUrl = "https://perfumereverie.com/wp-content/uploads/obrazki/htmljscss.webp",
                            Name = "Wprowadzenie do HTML5, CSS, JavaScript, jQuery",
                            Price = 300,
                            PublicationDate = new DateTime(2024, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = new Guid("9644c719-52df-4af1-bb6b-c89ed5aafc0b"),
                            Author = "Mariusz Jurczenko",
                            CategoryId = new Guid("d157b292-cf64-47df-815e-298c34ebc7a3"),
                            Description = "Wprowadzenie do Angular - Szybki start. Rozpoczęcie nowego projektu opartego o Angular wymaga stworzenia odpowiedniej struktury folderów, skonfigurowania środowiska, zainstalowania TypeScript, definicji typów, stworzenia pierwszego komponentu i wywołania funkcji bootstrap. ",
                            ImageUrl = "https://perfumereverie.com/wp-content/uploads/obrazki/Angular.webp",
                            Name = "Angular - Od Zera Do Bohatera",
                            Price = 300,
                            PublicationDate = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = new Guid("3da94357-fef3-4ca3-9a58-f5a267c92b7c"),
                            Author = "Mariusz Jurczenko",
                            CategoryId = new Guid("29db6e39-1b50-4001-960d-4451bbf2b2ad"),
                            Description = "Oglądasz właśnie nasz najbardziej podstawowy kurs. To jest miejsce, od którego powinieneś zacząć, jeśli nigdy w życiu nie napisałeś ani jednej linijki kodu, albo nawet jeśli to zrobiłeś i chcesz przejrzeć podstawy.",
                            ImageUrl = "https://perfumereverie.com/wp-content/uploads/obrazki/CoToJestProgramowanie.webp",
                            Name = "Co to jest programowanie",
                            Price = 0,
                            PublicationDate = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DevHobby.CourseFlow.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOrderPaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderTotal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("2f2b714d-d7dc-4b41-9fe9-4f6c8b9b44bb"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 300,
                            UserId = new Guid("947a072d-74f5-4047-8675-ef3b1c644f86")
                        },
                        new
                        {
                            OrderId = new Guid("c6f158ce-c515-4e55-b797-c9f9c7d98508"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 1000,
                            UserId = new Guid("3203e3cb-5175-479a-8cc1-ff2993310c16")
                        },
                        new
                        {
                            OrderId = new Guid("40ca3710-79f6-4dd0-bb77-b776ccc16483"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 600,
                            UserId = new Guid("9ec292d7-4fbb-4b28-83cf-4ebc36c46f77")
                        },
                        new
                        {
                            OrderId = new Guid("c4a7b7cc-12e2-4005-b585-6b38d31c08ab"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 800,
                            UserId = new Guid("b862b339-905e-4ffb-a75f-aff4bb4783ad")
                        },
                        new
                        {
                            OrderId = new Guid("a113de03-c149-4433-8986-d06d7af30402"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 600,
                            UserId = new Guid("2b57862f-ce11-44be-8be7-8aeea1f1fc55")
                        },
                        new
                        {
                            OrderId = new Guid("f633cd12-4a1a-4480-a701-ff133765e25a"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 400,
                            UserId = new Guid("59df54dd-a756-40a7-bd42-c37884878858")
                        },
                        new
                        {
                            OrderId = new Guid("13f8f25b-87d0-4c1c-b060-29f6115db06d"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 300,
                            UserId = new Guid("66a9d582-f899-455d-ab1b-002c4ff0feff")
                        },
                        new
                        {
                            OrderId = new Guid("b221702f-c18c-4be4-9b75-a778590079a9"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 600,
                            UserId = new Guid("4d614068-1d7e-4053-9d69-70c04be5a1e5")
                        },
                        new
                        {
                            OrderId = new Guid("bfe84eea-e393-4092-a78e-6467ec30c66f"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 200,
                            UserId = new Guid("24b8db77-b04a-4f8a-94e2-c01d89ed99b2")
                        },
                        new
                        {
                            OrderId = new Guid("1d08316d-d6ba-4cc2-bba1-42e0aa1acae3"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 400,
                            UserId = new Guid("0978fbc5-62b2-4679-8a76-08951b8715bb")
                        },
                        new
                        {
                            OrderId = new Guid("1fac403a-fcc1-4f47-aaad-07734d64f337"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 600,
                            UserId = new Guid("352d43bf-47d0-4bcf-b5e6-2608fab38bb4")
                        },
                        new
                        {
                            OrderId = new Guid("47ebb24b-eb9a-4ab6-b1f7-44d9eacb6fc2"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 800,
                            UserId = new Guid("3f42f780-60b8-4bae-b1b4-d5146a15935e")
                        },
                        new
                        {
                            OrderId = new Guid("34a131be-7afd-46eb-a902-0b566a08b17c"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 400,
                            UserId = new Guid("e9a9e856-c99d-4662-ba3e-a5123f4674a0")
                        },
                        new
                        {
                            OrderId = new Guid("df7d65b2-0c1c-4a0e-b9a3-76efbfcf4e4e"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 600,
                            UserId = new Guid("8b22cce4-cb1e-46b9-ab63-1216ba365f4b")
                        },
                        new
                        {
                            OrderId = new Guid("bf475bb5-2ede-4ee3-ad29-dd83c619cc4d"),
                            IsOrderPaid = true,
                            OrderPlaced = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 300,
                            UserId = new Guid("b8f9c1db-dd8b-42dc-bf3c-945a6be1e6e3")
                        });
                });

            modelBuilder.Entity("DevHobby.CourseFlow.Domain.Entities.Course", b =>
                {
                    b.HasOne("DevHobby.CourseFlow.Domain.Entities.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DevHobby.CourseFlow.Domain.Entities.Category", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
